
#app-nodejs takes Dockerfile.app from current directory

# sudo docker-compose up
# sudo docker-compose down --rmi all -v

version: "3"
services:
  web:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./public:/usr/share/nginx/html
    networks:
      - webnet
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app
    networks:
      - webnet
    depends_on:
      - db
  db:
    image: mongo
    volumes:
      - ./db:/data/db
    networks:
      - webnet
networks:
  webnet:
#    driver: bridge