
#app-nodejs takes Dockerfile.app from current directory

# sudo docker-compose up
# sudo docker-compose down --rmi all -v

version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    networks:
      - webnet
    depends_on:
      - app
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app
    networks:
      - webnet
    depends_on:
      - db
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    ports:
      - "27017:27017"
    volumes:
      - ./db:/data/db
    networks:
      - webnet
networks:
  webnet:
#    driver: bridge