
# sudo docker-compose -f docker-compose.escenario2.yml up
# sudo docker-compose -f docker-compose.escenario2.yml down --rmi all -v 
# sudo docker rmi $(sudo docker images -a -q) 

version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.nginx.escenario2
    ports:
      - "80:80"
    networks:
      - webnet
    depends_on:
      - app_5
  app_1:
    build:
      context: .
      dockerfile: Dockerfile.app.escenario2_1
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app
    networks:
      - webnet
    depends_on:
      - db
  app_2:
    build:
      context: .
      dockerfile: Dockerfile.app.escenario2_2
    ports:
      - "8082:8082"
    volumes:
      - ./app:/app
    networks:
      - webnet
    depends_on:
      - app_1
  app_3:
    build:
      context: .
      dockerfile: Dockerfile.app.escenario2_3
    ports:
      - "8083:8083"
    volumes:
      - ./app:/app
    networks:
      - webnet
    depends_on:
      - app_2
  app_4:
    build:
      context: .
      dockerfile: Dockerfile.app.escenario2_4
    ports:
      - "8084:8084"
    volumes:
      - ./app:/app
    networks:
      - webnet
    depends_on:
      - app_3
  app_5:
    build:
      context: .
      dockerfile: Dockerfile.app.escenario2_5
    ports:
      - "8085:8085"
    volumes:
      - ./app:/app
    networks:
      - webnet
    depends_on:
      - app_4
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    ports:
      - "27017:27017"
    volumes:
      - ./db:/data/db
    networks:
      - webnet
networks:
  webnet:
#    driver: bridge